@ProjectManagement.Api_HostAddress = https://localhost:5001

###

### Sign up
POST {{ProjectManagement.Api_HostAddress}}/api/auth/signup
Content-Type: application/json

{
  "username": "vlad",
  "email": "vlad@example.com",
  "password": "P@ssw0rd123"
}

###

### Sign in
POST {{ProjectManagement.Api_HostAddress}}/api/auth/signin
Content-Type: application/json

{
  "email": "vlad@example.com",
  "password": "P@ssw0rd123"
}

###

### Projects - list (requires X-User-Id header)
GET {{ProjectManagement.Api_HostAddress}}/api/projects/
X-User-Id: 1

###

### Projects - create
POST {{ProjectManagement.Api_HostAddress}}/api/projects/
Content-Type: application/json
X-User-Id: 1

{
  "name": "Sample project",
  "description": "Project created from .http file",
  "dueDateUtc": "2026-12-31T12:00:00Z",
  "createdByUserId": 1,
  "participatingUserIds": []
}

###

### Projects - delete
DELETE {{ProjectManagement.Api_HostAddress}}/api/projects/1
X-User-Id: 1

###

### Project invitations - creator sends invite to user 3 for project 1
POST {{ProjectManagement.Api_HostAddress}}/api/projects/1/invitations
Content-Type: application/json
X-User-Id: 1

{
  "invitedUserId": 3
}

###

### Project invitations - creator lists invitations for project 1
GET {{ProjectManagement.Api_HostAddress}}/api/projects/1/invitations
X-User-Id: 1

###

### Project invitations - invited user lists received invitations
GET {{ProjectManagement.Api_HostAddress}}/api/project-invitations/received
X-User-Id: 3

###

### Project invitations - invited user accepts invitation 1
POST {{ProjectManagement.Api_HostAddress}}/api/project-invitations/1/accept
X-User-Id: 3

###

### Project invitations - invited user declines invitation 1
POST {{ProjectManagement.Api_HostAddress}}/api/project-invitations/1/decline
X-User-Id: 3

###

### Project invitations - creator cancels invitation 1
DELETE {{ProjectManagement.Api_HostAddress}}/api/project-invitations/1
X-User-Id: 1

###
