@ProjectManagement.Api_HostAddress = https://localhost:5001

###

### Sign up
POST {{ProjectManagement.Api_HostAddress}}/api/auth/signup
Content-Type: application/json

{
  "username": "vlad",
  "email": "vlad@example.com",
  "password": "P@ssw0rd123"
}

###

### Sign in
POST {{ProjectManagement.Api_HostAddress}}/api/auth/signin
Content-Type: application/json

{
  "email": "vlad@example.com",
  "password": "P@ssw0rd123"
}

###
